image: python:3.9

stages:
  - compile
  - test
  - app
  - package

compile:
  stage: compile
  script:
    - ./compile
  artifacts:
    paths:
      - ./src_c/libconverter.so

test:
  stage: test
  script:
    - pip3 install pytest
    - python3 -m pytest > test.txt
    - cat test.txt
  artifacts:
    paths:
      - test.txt

app:
  stage: app
  script:
    - python3 main.py 20 c f > app.txt
    - cat app.txt
  artifacts:
    paths:
      - app.txt

package:
  stage: package
  script:
    - gzip -k test.txt app.txt
    - ls
  artifacts:
    paths:
      - test.txt.gz
      - app.txt.gz
