image: python:3.9

stages:
  - test
  - app
  - package

test:
  stage: test
  script:
    - apt install bash
    - pip3 install pytest
    - python3 -m pytest > test.txt
    - cat test.txt
  artifacts:
    paths:
      - test.txt

app:
  stage: app
  script:
    - python3 main.py 20 c f > app.txt
    - cat app.txt

package:
  stage: package
  script:
    - gzip -k test.txt app.txt
    - ls
  artifacts:
    paths:
      - test.txt.gz
