name: CI

on:
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile C code
        run: |
          cd src_c
          make shared
          cd ..        

     
