name: CI

on:
  push:
    branches: [ master ]


jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile C code
        run: |
          cd src_c
          make shared
          cd ..        
          
      - name: Copy artifact 
        uses: actions/upload-artifact@v2
        with:
          name: libconverter.so
          path: ./src_c/libconverter.so
     
  test:
     runs-on: ubuntu-latest
     needs: compile

     steps:
        - uses: actions/checkout@v2

        - name: Download shared labrary
          uses: actions/download-artifact@v2
          with:
            name: libconverter.so

        - name: Testing app
          run: |
            pip3 install pytest
            mv libconverter.so src_c/
            pytest > test.txt
            cat test.txt
