name: CI

on:
  pull_request:
    branches: [ master ]


jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile C code
        run: |
          cd src_c
          make shared
          cd ..        
          
      - name: Copy artifact 
        uses: actions/upload-artifact@v2
        with:
          name: libconverter.so
          path: ./src_c/libconverter.so
     
  test:
     runs-on: ubuntu-latest
     needs: compile

     steps:
        - uses: actions/checkout@v2

        - name: Download shared labrary
          uses: actions/download-artifact@v2
          with:
            name: libconverter.so

        - name: Testing app
          run: |
            pip3 install pytest
            mv libconverter.so src_c/
            pytest > test.txt
            cat test.txt
            
        - name: Copy result of testing
          uses: actions/upload-artifact@v2
          with:
            name: test
            path: test.txt
            
  app:
     runs-on: ubuntu-latest
     needs: compile

     steps:
        - uses: actions/checkout@v2

        - name: Download shared labrary
          uses: actions/download-artifact@v2
          with:
            name: libconverter.so
            
        - name: Move labrary
          run: mv libconverter.so src_c/
          
        - name: Exec app
          run: |
            python3 main.py 20 c f > app.txt
            cat app.txt
            
        - name: Copy result of testing
          uses: actions/upload-artifact@v2
          with:
            name: app
            path: app.txt
          
  package:
     runs-on: ubuntu-latest
     needs: [test, app]

     steps:
        - uses: actions/checkout@v2

        - name: Download testing result
          uses: actions/download-artifact@v2
          with:
            name: test

        - name: Download app result
          uses: actions/download-artifact@v2
          with:
            name: app

        - name: Package
          run: |
            gzip -k test.txt app.txt
            ls

        - name: Copy packed result
          uses: actions/upload-artifact@v2
          with:
            name: results
            path: |
              text.txt.gz
              app.txt.gz
